"""Crawler for https://ssr1.scrape.center/ (all pages).

ssr1 is a server-side-rendered movie site with no anti-scraping, so all data
is already in the HTML. Note: the site's TLS certificate is expired, so we
disable verification.
"""
import csv
import io
import os
import re
import sys
import requests
import urllib3
from html import unescape
from PIL import Image as PILImage
from openpyxl import Workbook
from openpyxl.drawing.image import Image as XLImage
from openpyxl.styles import Alignment, Font

from db import save_movies, DB_FILE

urllib3.disable_warnings()  # site's TLS cert is expired
sys.stdout.reconfigure(encoding="utf-8")

BASE_URL = "https://ssr1.scrape.center/page/{}"
SITE = "https://ssr1.scrape.center"
CSV_FILE = "movies.csv"
XLSX_FILE = "movies.xlsx"
POSTER_DIR = "posters"
POSTER_W = 90  # embedded thumbnail width in px (height scales to keep aspect)

FIELDS = ["title", "categories", "regions", "minutes",
          "release_date", "score", "rating", "detail_url", "cover_url"]


def fetch(url):
    resp = requests.get(url, verify=False, timeout=20)
    if resp.status_code != 200:  # beyond the last page the site returns 500
        return None
    return resp.text


def parse(html):
    movies = []
    cards = re.split(r'class="el-card item', html)[1:]
    for card in cards:
        detail = re.search(r'href="(/detail/\d+)"', card)
        cover = re.search(r'src="([^"]+)"\s+class="cover"', card)
        name = re.search(r'class="name">\s*<h2[^>]*>([^<]+)</h2>', card)
        cats = re.findall(r'class="el-button category[^"]*">\s*<span[^>]*>([^<]+)</span>', card)
        infos = re.findall(r'class="m-v-sm info">(.*?)</div>', card, re.S)
        score = re.search(r'class="score[^"]*">\s*([\d.]+)', card)
        rating = re.search(r'role="slider"\s+aria-valuenow="([\d.]+)"', card)

        def clean(block):
            return [t.strip() for t in re.findall(r'>([^<>]+)<', block) if t.strip()]

        # first info line is "regions / duration"; second is the release date
        info_parts = clean(infos[0]) if infos else []
        regions = info_parts[0] if info_parts else ""
        minutes = next((p for p in info_parts if "分钟" in p), "")
        release = " ".join(clean(infos[1])) if len(infos) > 1 else ""
        release = release.replace(" 上映", "").strip()

        movies.append({
            "title": unescape(name.group(1).strip()) if name else "",
            "categories": ", ".join(cats),
            "regions": regions,
            "minutes": minutes,
            "release_date": release,
            "score": score.group(1) if score else "",
            "rating": rating.group(1) if rating else "",
            "detail_url": SITE + detail.group(1) if detail else "",
            "cover_url": cover.group(1) if cover else "",
        })
    return movies


def download_poster(url, dest):
    """Download a poster, save a width-POSTER_W thumbnail, return (w, h) in px."""
    resp = requests.get(url, verify=False, timeout=30)
    resp.raise_for_status()
    img = PILImage.open(io.BytesIO(resp.content)).convert("RGB")
    h = round(img.height * POSTER_W / img.width)
    img = img.resize((POSTER_W, h))
    img.save(dest, "JPEG")
    return POSTER_W, h


def write_excel(movies):
    os.makedirs(POSTER_DIR, exist_ok=True)
    wb = Workbook()
    ws = wb.active
    ws.title = "movies"

    # column A = poster, then rank + text fields
    headers = ["poster", "rank"] + FIELDS
    ws.append(headers)
    for cell in ws[1]:
        cell.font = Font(bold=True)

    ws.column_dimensions["A"].width = POSTER_W / 7 + 2  # px -> char width
    for col, name in zip("CDEFGHIJK", FIELDS):
        ws.column_dimensions[col].width = 40 if name in ("detail_url", "cover_url", "title") else 14

    for i, m in enumerate(movies, 1):
        row = i + 1
        ws.cell(row=row, column=2, value=i)
        for col, name in enumerate(FIELDS, start=3):
            ws.cell(row=row, column=col, value=m[name]).alignment = Alignment(
                vertical="center", wrap_text=True)

        if m["cover_url"]:
            dest = os.path.join(POSTER_DIR, f"{i}.jpg")
            try:
                w, h = download_poster(m["cover_url"], dest)
                img = XLImage(dest)
                img.width, img.height = w, h
                ws.add_image(img, f"A{row}")
                ws.row_dimensions[row].height = h * 0.75 + 4  # px -> points
                print(f"  poster {i}/{len(movies)}: {m['title']}")
            except Exception as e:
                print(f"  poster {i} failed: {e}")

    wb.save(XLSX_FILE)


def write_readme(movies):
    lines = [
        "# ssr1.scrape.center Movie List",
        "",
        f"Scraped from <https://ssr1.scrape.center/> — {len(movies)} movies across 10 pages.",
        "Generated by `crawler.py`. Posters are stored in `posters/`.",
        "",
        "| # | Poster | Title | Categories | Regions | Minutes | Release | Score | Rating | Detail |",
        "|---|--------|-------|------------|---------|---------|---------|-------|--------|--------|",
    ]
    for i, m in enumerate(movies, 1):
        poster = f'<img src="{POSTER_DIR}/{i}.jpg" width="80">'
        detail = f"[link]({m['detail_url']})" if m["detail_url"] else ""
        lines.append(
            f"| {i} | {poster} | {m['title']} | {m['categories']} | {m['regions']} | "
            f"{m['minutes']} | {m['release_date']} | {m['score']} | {m['rating']} | {detail} |"
        )
    with open("README.md", "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def crawl_all(save_html=False):
    """Crawl every page and return the full list of movie dicts."""
    all_movies = []
    page = 1
    while True:
        html = fetch(BASE_URL.format(page))
        if html is None:  # past the last page (site returns 500)
            print(f"No page {page}, stopping.")
            break

        movies = parse(html)
        if not movies:  # empty page -> we've passed the last real page
            print(f"Page {page} is empty, stopping.")
            break

        if save_html:
            with open(f"page{page}.html", "w", encoding="utf-8") as f:
                f.write(html)

        print(f"Page {page}: {len(movies)} movies")
        all_movies.extend(movies)
        page += 1
    return all_movies


def ensure_posters(movies):
    """Download any posters not already present in POSTER_DIR."""
    os.makedirs(POSTER_DIR, exist_ok=True)
    for i, m in enumerate(movies, 1):
        dest = os.path.join(POSTER_DIR, f"{i}.jpg")
        if m["cover_url"] and not os.path.exists(dest):
            try:
                download_poster(m["cover_url"], dest)
            except Exception as e:
                print(f"  poster {i} failed: {e}")


def main():
    all_movies = crawl_all(save_html=True)

    # utf-8-sig so Excel renders the Chinese text correctly
    with open(CSV_FILE, "w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["rank"] + FIELDS)
        writer.writeheader()
        for i, m in enumerate(all_movies, 1):
            writer.writerow({"rank": i, **m})

    save_movies(all_movies)  # movie.db

    print("=" * 50)
    print(f"Downloading posters and building {XLSX_FILE} ...")
    write_excel(all_movies)

    print("=" * 50)
    print(f"Total: {len(all_movies)} movies")
    write_readme(all_movies)
    print(f"Saved {CSV_FILE}, {DB_FILE}, {XLSX_FILE}, README.md (posters in {POSTER_DIR}/)")


if __name__ == "__main__":
    main()
